### ISSUE TITLE
Expo sdk v.20

### ISSUE THREAD

**Issue by drewbietron** [dalcib/jest-expo-ts#2]
Tried running this with the newest Expo sdk (v.20) and it gives back -- 

`ReferenceError: __DEV__ is not defined`

**Comment by dalcib** [comment]
@drewbietron, I updated this package to use expo-jest 20.0.0.
Can you test to see if the problem is solved?

**Comment by drewbietron** [comment]
@dalcib - The package is still at v19 - https://www.npmjs.com/package/jest-expo-ts

**Comment by cmodien** [comment]
should publish this to npm

**Comment by dalcib** [comment]
Oh, I'm sorry. I thought I had published. It is done.
