### ISSUE TITLE
Error after expo-sdk upgrade from 18 to 20

### ISSUE THREAD

**Issue by vyemialyanchyk** [dalcib/jest-expo-ts#3]
I assume these are related with jest-expo-ts:
https://github.com/react-community/create-react-native-app/issues/390

after these changes:
app.json:
{ "expo": { "sdkVersion": "18.0.0", ...
==>
{ "expo": { "sdkVersion": "20.0.0", ...

package.json:
`
"devDependencies": {
"jest-expo": "18.0.0",
"jest-expo-ts": "18.0.1",
...
"dependencies": {
"expo": "18.0.0",
"react-native": "0.45.1",
...

==>
"devDependencies": {
"jest-expo": "20.0.0",
"jest-expo-ts": "20.0.0",
...
"dependencies": {
"expo": "20.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
...

`

gets error with

npm start
react-native-scripts start
4:27:29 PM: Starting packager...
ERROR STARTING PACKAGER
Starting React Native packager...
Scanning 779 folders for symlinks in .......\node_modules (17ms)

EISDIR: illegal operation on a directory, read
4:33:49 PM: Stopping packager...
4:33:49 PM: Packager stopped.

practically the same problem with update to version 19:

3:31:45 PM: Starting packager...
***ERROR STARTING PACKAGER***
Warning: 'react-native' peer depencency missing. Run `npm ls` in C:\Test\testProj to see full warning.

If there is an issue running your project, please run `npm install` in C:\Test\testProj and restart.
Starting React Native packager...
Scanning 787 folders for symlinks in C:\Test\testProj\node_modules (16ms)

EISDIR: illegal operation on a directory, read.

Could you please suggest howto resolve the problem?

**Comment by dalcib** [comment]
You need typescript as devDependency in the package.json, because it is a peer dependency of this package. Then try `npm i`

**Comment by vyemialyanchyk** [comment]
typescript is as devDependency, above I've just provide short snippet, here is a whole:
`	"devDependencies": {
		"jest-expo": "20.0.0",
		"jest-expo-ts": "20.0.0",
		"mobx": "3.2.2",
		"mobx-react": "4.2.2",
		"react-native-scripts": "1.3.0",
		"react-native-typescript-transformer": "1.1.3",
		"react-test-renderer": "16.0.0-alpha.12",
		"typescript": "2.4.2"
	},
	"dependencies": {
		"@types/jest": "20.0.7",
		"@types/react": "15.6.1",
		"@types/react-native": "0.44.19",
		"@types/react-test-renderer": "15.5.3",
		"expo": "20.0.0",
		"lodash": "4.17.4",
		"moment": "2.18.1",
		"react": "16.0.0-alpha.12",
		"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
		"react-native-vector-icons": "4.3.0",
		"tslib": "1.7.1"
	}
`

**Comment by dalcib** [comment]
@vyemialyanchyk, please, try to configure  `app.json` according to the recommendation of https://github.com/ds300/react-native-typescript-transformer, to see if it works.
I can't test because am traveling right now.

**Comment by dalcib** [comment]
It's necessary to add `/index.js` to the `transformer` property in app.json to make it work with Expo version 19. Don't know why. See https://github.com/expo/expo/issues/428#issuecomment-318491235.
```
"transformer": "node_modules/react-native-typescript-transformer/index.js"
```
Thanks to @janaagaard75
