### ISSUE TITLE
Could you please to upgrade the dependence version of "jest-expo" to the latest?

### ISSUE THREAD

**Issue by denghejun** [dalcib/jest-expo-ts#4]
The reason why I ask you to upgrade is this: https://github.com/expo/expo/issues/645

**Comment by dalcib** [comment]
It is done, with jest-expo 21.0.2

**Comment by denghejun** [comment]
thanks

发自我的 iPhone

在 2017年9月25日，上午3:22，Dalci de Jesus Bagolin <notifications@github.com<mailto:notifications@github.com>> 写道：


It is done, with jest-expo 21.0.2
